# Generated by Django 3.2.16 on 2022-12-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20221201_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='entregue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='pago',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
