# Generated by Django 3.2.16 on 2022-12-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20221201_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='valor',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
