# Generated by Django 3.2.16 on 2022-12-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_order_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
