# Generated by Django 3.2.16 on 2022-12-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_order_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='notavailable', max_length=255),
            preserve_default=False,
        ),
    ]
