# Generated by Django 3.2.16 on 2022-12-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_link',
            field=models.URLField(null=True),
        ),
    ]
