# Generated by Django 3.2.16 on 2022-12-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_remove_order_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payer_phone',
            field=models.CharField(default=0, max_length=18),
            preserve_default=False,
        ),
    ]
