# Generated by Django 3.2.16 on 2022-12-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_order_payer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payer_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
