# Generated by Django 3.2.16 on 2022-11-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('imagem_url', models.URLField(null=True)),
                ('valor', models.IntegerField()),
                ('valor_com_desconto', models.IntegerField()),
                ('desconto', models.BooleanField()),
                ('ativo', models.BooleanField()),
                ('quantidade', models.IntegerField()),
                ('tamanho', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
