# Generated by Django 3.2.16 on 2022-12-02 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_vendedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vendedor',
        ),
    ]
